baseURL = "https://palSagnik.github.io/core-dump/"
locale = "en-us"
title = "core-dump"
theme = "stdout"

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML"]

[params]
  description = "A minimal dev blog"
  author = "Sagnik Pal"
  showReadingTime = true

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = false
    noClasses = true
  [markup.goldmark.renderer]
    unsafe = true

[taxonomies]
  tag = "tags"

[[menus.main]]
  name    = "home"
  pageRef = "/"
  weight  = 1

[[menus.main]]
  name    = "log"
  pageRef = "posts"
  weight  = 2

[[menus.main]]
  name    = "tags"
  pageRef = "tags"
  weight  = 3

[[menus.main]]
  name    = "about"
  pageRef = "about"
  weight  = 4

